language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t jayesh0099/docker-react .
    
script:
    - docker run -e CI=true jayesh0099/docker-react npm run test -- --coverage