language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t jayesh0099/docker-react .
    
script:
    - docker run -e CI=true jayesh0099/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "Docker"
    env: "Docker-env-1"
    bucket_name: "elasticbeanstalk-ap-south-1-290320295720"
    bucket_path: "Docker"
    on:
        branch: master    
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
    
    